server:
  port: 8090

spring:
  application:
    name: awesome-apigateway-service

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

zuul:
  routes:
    js-account-service:
      service-id: js-account-service
      #url: http://account.skcc.co.kr
      url: http://account:8180
      path: /account/**
    js-cart-service:
      service-id: js-cart-service
      #url: http://cart.skcc.co.kr
      url: http://cart:8181
      path: /cart/**
    js-order-service:
      service-id: js-order-service
      #url: http://order.skcc.co.kr
      url: http://order:8182
      path: /order/**
    js-payment-service:
      service-id: js-payment-service
      #url: http://payment.skcc.co.kr
      url: http://payment:8183
      path: /payment/**
    js-product-service:
      service-id: js-product-service
      #url: http://product.skcc.co.kr
      url: http://product:8184
      path: /product/**
