server:
  port: 8090


logging:
  level:
    com.amazonaws.xray: DEBUG
    org.springframework.boot: INFO
    org.springframework.core : INFO

spring:
  application:
    name: awesome-apigateway-service
  config:
    import: 
      - optional:application-prd.yml

  # sleuth:
  #   otel:
  #     config:
  #       trace-id-ratio-based: 100
  #     exporter:
  #       otlp:
  #         endpoint: http://collector:4317




management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

zuul:
  routes:
    js-account-service:
      service-id: js-account-service
      # url: http://account:8180
      url: http://localhost:8180
      path: /account/**
    js-cart-service:
      service-id: js-cart-service
      # url: http://cart:8181
      url: http://localhost:8181
      path: /cart/**
    js-order-service:
      service-id: js-order-service
      # url: http://order:8182
      url: http://localhost:8182
      path: /order/**
    js-payment-service:
      service-id: js-payment-service
      # url: http://payment:8183
      url: http://localhost:8183
      path: /payment/**
    js-product-service:
      service-id: js-product-service
      # url: http://product:8184
      url: http://localhost:8184
      path: /product/**
